name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt-get install cmake ninja-build clang protobuf-compiler-grpc libgrpc++-dev libgtest-dev libgmock-dev libedit-dev libspdlog-dev libstdc++-14-dev
    - name: build release
      run: CXX=clang++ CC=clang cmake --workflow --preset release
    - name: build debug
      run: CXX=clang++ CC=clang cmake --workflow --preset debug

