name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: archive repository
      run: git archive --format=tar.gz -o cashmere.tar.gz HEAD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag snpd/cashmere:$(date +%s) --target test-runtime
